title: "DigiChem Lab"
author: "Tiago Rodrigues"
description: "Faculty of Pharmacy, University of Lisbon"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header
show_social: true 

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Research", file: "research.md"}
  - {title: "Publications", file: "publications.md"}
  - {title: "About Tiago", file: "tiago.md"}
  - {title: "Team", file: "team.md"}
  - {title: "News", file: "news.md"}
  - {title: "Software", file: "software.md"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:tiago.rodrigues@ff.ulisboa.pt"}
  - {title: Github, icon: github, url: "https://github.com/digichem"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/tiago_medchem"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
